from __future__ import annotations

import argparse
import json
import uuid
from dataclasses import replace
from pathlib import Path
from typing import Any

from faker import Faker

from connectathon.shn_medilacra_crd import (
    SHN_PAYER_IDENTIFIER_SYSTEM,
    SHN_ROUTE_00301,
    build_crd_order_sign_request,
    crd_expected_invariants,
)
from connectathon.shn_mvp0 import (
    CASE_NAMESPACE,
    SHNMVP0Reality,
    build_reality,
    reality_manifest,
)


LUMBAR_FUSION_CPT = "22633"
LUMBAR_FUSION_DISPLAY = "Lumbar spinal fusion"
LUMBAR_FUSION_QUESTIONNAIRE = "http://example.org/fhir/Questionnaire/LumbarSpinalFusion"
ICD10_CM_SYSTEM = "http://hl7.org/fhir/sid/icd-10-cm"
LUMBAR_SPONDYLOLISTHESIS_ICD10 = "M43.16"
LUMBAR_SPONDYLOLISTHESIS_DISPLAY = "Spondylolisthesis, lumbar region"
SPINE_TAXONOMY = "207XS0117X"
SPINE_SPECIALTY = "Orthopaedic Surgery of the Spine"


def _scenario_id(seed: int, label: str) -> str:
    value = uuid.uuid5(CASE_NAMESPACE, f"{seed}:lumbar-fusion:{label}")
    return value.hex[:16]


def _provider_name(seed: int) -> str:
    fake = Faker()
    fake.seed_instance(seed + 22633)
    parts = fake.name().split()
    return f"{parts[-1].upper()}, {parts[0].upper()}"


def build_lumbar_fusion_reality(seed: int = 43) -> SHNMVP0Reality:
    """Build a coherent lumbar-fusion scenario from the deterministic MVP-0 patient.

    Patient, coverage and source payer stay fixed for the same seed so the
    experiment changes the clinical scenario rather than the network identity.
    The encounter and order receive new identities so an earlier MRI order is
    never redefined as surgery.
    """
    base = build_reality(seed)

    encounter_id = f"ENC-{_scenario_id(seed, 'encounter')}"
    visit_number = f"VN-{_scenario_id(seed, 'visit')}"
    account_number = f"ACC-{_scenario_id(seed, 'account')}"
    service_request_id = f"SR-{_scenario_id(seed, 'service-request')}"
    provider_id = f"SPINE-{_scenario_id(seed, 'spine-surgeon')}"
    provider_name = _provider_name(seed)

    encounter = replace(
        base.encounter,
        encounter_id=encounter_id,
        visit_number=visit_number,
        account_number=account_number,
        patient_class="OUTPATIENT",
        assigned_patient_location="SPINE_CLINIC1",
        hospital_service="ORTHO",
        ordering_provider_id=provider_id,
        ordering_provider_name=provider_name,
        attending_provider_id=provider_id,
        attending_provider_name=provider_name,
        attending_provider_taxonomy=SPINE_TAXONOMY,
        attending_provider_specialty=SPINE_SPECIALTY,
        placer_order_number=service_request_id,
        filler_order_number=f"FIL-{_scenario_id(seed, 'filler-order')}",
        place_of_service_code="22",
        place_of_service_description="On Campus-Outpatient Hospital",
    )

    transaction = replace(
        base.transaction,
        transaction_id=str(
            uuid.uuid5(CASE_NAMESPACE, f"{seed}:lumbar-fusion:transaction")
        ),
        encounter_id=encounter_id,
        transaction_amount=18500.00,
        unit_cost=12500.00,
        fee_schedule="SPINE-SURG",
        authorization_number=f"AUTH-{_scenario_id(seed, 'authorization')}",
        billing_provider_id=provider_id,
        billing_provider_name=provider_name,
    )

    return replace(
        base,
        case_id=f"shn_lumbar_fusion_{seed:04d}",
        encounter=encounter,
        transaction=transaction,
        service_request_id=service_request_id,
        therapy_weeks=max(base.therapy_weeks, 12),
        neuro_deficit=False,
        prior_imaging=True,
        imaging_confirms_instability_or_spondylolisthesis=True,
        diagnosis_system=ICD10_CM_SYSTEM,
        diagnosis_code=LUMBAR_SPONDYLOLISTHESIS_ICD10,
        diagnosis_display=LUMBAR_SPONDYLOLISTHESIS_DISPLAY,
        service_code=LUMBAR_FUSION_CPT,
        service_display=LUMBAR_FUSION_DISPLAY,
    )


def expected_shn_behavior() -> dict[str, Any]:
    """Document the route-00301 rule we expect this scenario to exercise."""
    return {
        "payer_route": {
            "system": SHN_PAYER_IDENTIFIER_SYSTEM,
            "value": SHN_ROUTE_00301,
        },
        "service_code": LUMBAR_FUSION_CPT,
        "expected_crd": {
            "covered": "conditional",
            "pa-needed": "auth-needed",
            "doc-needed": "clinical",
            "doc-purpose": "withpa",
            "info-needed": "OTH",
            "questionnaire": LUMBAR_FUSION_QUESTIONNAIRE,
        },
        "note": (
            "This is an expected live payer response from SHN's documented "
            "00301 lumbar-fusion test rule, not a value generated by MediLacra."
        ),
    }


def build_lumbar_fusion_case(
    seed: int = 43,
    payer_route: str = SHN_ROUTE_00301,
) -> dict[str, Any]:
    reality = build_lumbar_fusion_reality(seed)
    invariants = crd_expected_invariants(reality, payer_route=payer_route)
    invariants["scenario"] = "lumbar-fusion"
    invariants["clinical_facts"] = {
        "conservative_therapy_weeks": reality.therapy_weeks,
        "neuro_deficit": reality.neuro_deficit,
        "prior_imaging": reality.prior_imaging,
        "imaging_confirms_instability_or_spondylolisthesis": (
            reality.imaging_confirms_instability_or_spondylolisthesis
        ),
        "diagnosis": {
            "system": reality.diagnosis_system,
            "code": reality.diagnosis_code,
            "display": reality.diagnosis_display,
        },
    }
    return {
        "reality": reality_manifest(reality),
        "crd_request": build_crd_order_sign_request(
            reality,
            payer_route=payer_route,
        ),
        "expected_invariants": invariants,
        "expected_shn_behavior": expected_shn_behavior(),
    }


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def write_lumbar_fusion_case(
    case: dict[str, Any],
    output_dir: str | Path,
) -> Path:
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)
    (path / "reality.json").write_bytes(_json_bytes(case["reality"]))
    (path / "crd_request.json").write_bytes(_json_bytes(case["crd_request"]))
    (path / "expected_invariants.json").write_bytes(
        _json_bytes(case["expected_invariants"])
    )
    (path / "expected_shn_behavior.json").write_bytes(
        _json_bytes(case["expected_shn_behavior"])
    )
    return path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the MediLacra lumbar-fusion reality and its SHN CRD projection"
        )
    )
    parser.add_argument("--seed", type=int, default=43)
    parser.add_argument("--payer-route", default=SHN_ROUTE_00301)
    parser.add_argument(
        "--out",
        default="connectathon/results/shn_lumbar_fusion",
    )
    args = parser.parse_args()

    case = build_lumbar_fusion_case(
        seed=args.seed,
        payer_route=args.payer_route,
    )
    out = write_lumbar_fusion_case(
        case,
        Path(args.out) / case["reality"]["case_id"],
    )
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
